# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_oauthweibouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthweibouser',
            name='access_token',
            field=models.CharField(db_index=True, max_length=64, verbose_name='weibotoken'),
        ),
    ]
